### ISSUE TITLE
Event Single Page : Unable to select "AM and PM" on timetable start and end hour.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#114]
![image](https://cloud.githubusercontent.com/assets/12791909/9951366/267feb36-5df8-11e5-92d8-b20379ac58de.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

This is already a plugin functionality, in which the user already know how to use the plugin.
see documentation:
https://www.behance.net/gallery/15285847/Timetable-Responsive-Schedule-For-WordPress 

THanks,
Christian

**Comment by ermatitan** [comment]
plug-in restriction
