### ISSUE TITLE
Event Single Page: Today Upcoming Events does not display's all of the day's upcoming events.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#115]
![image](https://cloud.githubusercontent.com/assets/12791909/9951390/78006bb6-5df8-11e5-94df-5f53341bb22d.png)

![image](https://cloud.githubusercontent.com/assets/12791909/9951401/8ccbdb02-5df8-11e5-952a-3e18dd7da40a.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

I think this is a plugin issue, i am still waiting for Ricky's for his feedback on this issues, when adding upcoming events, Appearance >widgets, it will not display today events. will label this one as question and wontfix.

Thanks,
Christian
