### ISSUE TITLE
Personal Training Single Page - About Me static text not displayed.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#135]
![image](https://cloud.githubusercontent.com/assets/12791909/9954817/a1aa5b72-5e1e-11e5-922d-1d2d97512035.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

We have made this dynamic, so that user can put any tags in the content, PS updated.
https://docs.google.com/spreadsheets/d/1hICIP7GD3_Ik7mRpleO7lMabbAvFXCHTzpxZDhV0j9E/edit#gid=2035631399

Thanks,
Christian
