### ISSUE TITLE
The Team - About Me static field should also be displayed on The team page as they are design the same way as per project scope

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#136]
![image](https://cloud.githubusercontent.com/assets/12791909/9954863/f97ab66c-5e1e-11e5-93b1-a59e1ee79208.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

You can just put <h3>About Me</h3> in the backend content.

Thanks,
Christian
