### ISSUE TITLE
General: Header 2 -6 does not have a 2px decrements as per Titan standard.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#14]
https://knowledgebase.titanweb.com.au/implementation-practices/page-section-contents/page-content-styling

**Comment by ermatitan** [comment]
not fix

**Comment by christiancebudigital** [comment]
Hi Erma,

Please provide page links, as i dont know where you found the pages you are referring to.

Thanks,
Christian

**Comment by ermatitan** [comment]
Please check 
http://evolutionmma.stage.titanweb.com.au/is-mma-for-me/

Header 2 - 35px
Header 3 - 33px
Header 4 - 31px
Header 5 - 29px
Header 6 - 28px - it should be 27px
