### ISSUE TITLE
Mobile - Footer Gravity Form: Error message overlaps with the send enquiry button.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#151]
S4 , iTouch

![image](https://cloud.githubusercontent.com/assets/12791909/10068180/d8db2f30-62d4-11e5-8eac-a2f6df680db7.png)

**Comment by ermatitan** [comment]
not fix... the error message now overlaps with the Your Message container.
![image](https://cloud.githubusercontent.com/assets/12791909/10154175/cea5d75c-6696-11e5-800f-0e19b5884e09.png)

**Comment by ermatitan** [comment]
not fix
Ipad Air
![image](https://cloud.githubusercontent.com/assets/12791909/10214467/1edd33d6-684b-11e5-9cf8-33f03e956a19.png)

S4
![image](https://cloud.githubusercontent.com/assets/12791909/10214510/762fe0a2-684b-11e5-8e0d-a2b5223d49e8.png)

**Comment by ermatitan** [comment]
not fix

**Comment by ermatitan** [comment]
not fix

**Comment by christiancebudigital** [comment]
Hi Erma,

We cant replicate your error in S4, since we dont have the actual device here, but it is working on our end.

Thanks,
Christian

**Comment by ermatitan** [comment]
Hello Christian, 

I can recreate the issue using chrome emulator as will as in the actual device (S4 and iTouch).  Send Inquiry button cannot be seen after creating the submission error.

**Comment by ermatitan** [comment]
not fix on itouch portrait view.

![image](https://cloud.githubusercontent.com/assets/12791909/10420393/82f3c394-70c5-11e5-8ac4-e597e45a8b04.png)
