### ISSUE TITLE
Mobile - Homepage : a blank space were observed on lead-in images on mobile devices

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#153]
All Devices

![image](https://cloud.githubusercontent.com/assets/12791909/10068563/ecc7e59e-62d7-11e5-94fd-81a2f1201ab9.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

please upload image that are bigger in sizes, and also, please upload images that have no lines on the top, see image that ive downloade on the site. it has a line on the top. 
![image issue](https://cloud.githubusercontent.com/assets/11186331/10129113/1c55f356-65ed-11e5-90f8-d5890257a218.jpg)

Thanks,
Christian
