### ISSUE TITLE
Class Timetable : Newly created event not displayed on class timetable

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#164]
I have created a new event http://evolutionmma.stage.titanweb.com.au/events/friday-madness/ and it does not displayed on the Homepage and Class page timetable.

![image](https://cloud.githubusercontent.com/assets/12791909/10154893/eed4f978-669f-11e5-86b0-bf59e16d8429.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

When adding new event, you also need to update its shortdode, in homepage and classpage in dashboard, see attached file.

Thanks,
Christian
![classtimetable](https://cloud.githubusercontent.com/assets/11186331/10156673/18bac36a-66b6-11e5-867b-3f87dd07d49d.jpg)

**Comment by ermatitan** [comment]
Hello Christian, 
Why is it that the newly created events before was automatically added to the time table without updating any short code in the class page?

**Comment by christiancebudigital** [comment]
Hi Erma,

Based on what i know, upon using this plugin, plugin uses shortcode in order the events to take effect, the timetable uses its default events found in the database, if actual data are now stored in the database, it will be then be replaced with the current ones., this is a paid plugin that the client want in their site, see Design Brief, i think the client know how to use this plugin. 

Thanks,
Christian

**Comment by ermatitan** [comment]
Hello Christian, 

We can't assume that the client knows how to use this plugin. It was implemented before that the event created was automatically updated to the timetable, so I think there is no issue in implementing it back. Thanks.

**Comment by christiancebudigital** [comment]
Hi Erma,

Your question was, "Why is it that the newly created events before was automatically added to the time table without updating any short code in the class page", when we created events, the short code will do its function, to display any events created on the page, from there, we can customize the short codes in the setting, if there are no events in the custom post. there will be no output in frontend, so basically, to make the class timetable dynamic, we need to put it in a shortcode, for us to edit the content of the classtimetable in the site, just like contact us, i think it is also shortcoded. thanks.

**Comment by ermatitan** [comment]
Hello Christian, 

Based on the user guide, to be able to add anything to the timetable , you just have to create an event. If the implementation really have to be short coded, then you need to update the site user guide. thanks

**Comment by christiancebudigital** [comment]
Hi Erma,

Ive attached here the updated Document for the user guide.

Thanks,
Christian
[Updarted_Walkthrough on how to edit site - evolutionmma.docx](https://github.com/titan-cebu/Evolution-MMA/files/9007/Updarted_Walkthrough.on.how.to.edit.site.-.evolutionmma.docx)

**Comment by ermatitan** [comment]
user guide updated.
