### ISSUE TITLE
Event /Classes with redirect URL (external link) does not open to a new tab.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#171]
![image](https://cloud.githubusercontent.com/assets/12791909/10215869/c2a6bb98-6857-11e5-9a2d-e43d2e5aa587.png)

**Comment by christiancebudigital** [comment]
Hi
![aaaa](https://cloud.githubusercontent.com/assets/11186331/10240210/a359a64c-690b-11e5-83d5-0d14c85f8181.jpg)
 Erma,

I think you added a fb link in the backend, see attached link of the sample event. anyways it is now deleted

Thanks,
Christian

**Comment by ermatitan** [comment]
Hello Christian, 
Yes I have added that fb link in the back end to check if an external link will open in the a new tab and it turns out that it doesn't.  Thanks

**Comment by christiancebudigital** [comment]
I am not able to edit code on backend, this is a plugin code, let me know your idea on this.thanks.

**Comment by ermatitan** [comment]
wont fix as this is a plugin issue
