### ISSUE TITLE
IE : Join the Evolution field input boxes not aligned.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#173]
![image](https://cloud.githubusercontent.com/assets/12791909/10216211/eafe6ad0-6859-11e5-80b9-1224fb181487.png)

**Comment by ermatitan** [comment]
not fix

**Comment by christiancebudigital** [comment]
please clear cache, thanks,
![evo](https://cloud.githubusercontent.com/assets/11186331/10271227/580e012e-6b3b-11e5-80f6-59087c8b5170.jpg)

**Comment by ermatitan** [comment]
This problem reoccurs again.

![Uploading image.png…]()

**Comment by ermatitan** [comment]
I have cleared my cache, this problem re-occurs again in Firefox.

![image](https://cloud.githubusercontent.com/assets/12791909/10421338/00ff5a2e-70d9-11e5-9896-9a63a66811de.png)
