### ISSUE TITLE
IE : Join the Evolution message field input box touches with the Send inquiry button

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#174]
![image](https://cloud.githubusercontent.com/assets/12791909/10216232/11957936-685a-11e5-80ba-db4faea1ca6e.png)

**Comment by ermatitan** [comment]
not fix

**Comment by christiancebudigital** [comment]
![evo](https://cloud.githubusercontent.com/assets/11186331/10271230/61cebf3c-6b3b-11e5-9432-5b53c9af444e.jpg)
please clear cache, thanks

**Comment by ermatitan** [comment]
not fix

**Comment by ermatitan** [comment]
hello Christian, 

I have already cleared my cache and verified also to other computer using  IE browser and problem still occurs. 

![image](https://cloud.githubusercontent.com/assets/12791909/10355668/32759978-6da1-11e5-9396-3889af733768.png)
