### ISSUE TITLE
Join the evolution submission error overflows to its container.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#184]
![image](https://cloud.githubusercontent.com/assets/12791909/10442567/3a010afe-7186-11e5-811e-9036677dd703.png)

**Comment by ermatitan** [comment]
not fix

**Comment by ermatitan** [comment]
not fix on IE

**Comment by christiancebudigital** [comment]
![ie](https://cloud.githubusercontent.com/assets/11186331/10476407/1bbac74c-7280-11e5-9192-7d61d62fceff.jpg)
This is working in my end, please see file attached.
