### ISSUE TITLE
Contact Us menu goes down when browser is resized.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#185]
![image](https://cloud.githubusercontent.com/assets/12791909/10472846/e17631a2-7257-11e5-9517-3af33fb570f7.png)

**Comment by ermatitan** [comment]
can still recreate using 1010x507 screen dimension

**Comment by christiancebudigital** [comment]
![firefox](https://cloud.githubusercontent.com/assets/11186331/10476401/08c6f5b6-7280-11e5-9a81-e5809d085d8c.jpg)
This is working in my end, please clear cache.
