### ISSUE TITLE
Trainer : Achievements / Qualifications header still displays on front-end even if there is no data added in the backend.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#34]
![image](https://cloud.githubusercontent.com/assets/12791909/9712780/a675b554-557f-11e5-8132-44a1e6e2cd2b.png)

**Comment by christiancebudigital** [comment]
HI Erma,

as you can see, there are rows on acf fields, which means content can be applied or it is enabled, but if we delete the row content on the site, achievement / qualifications, will not be displayed.

Thanks,
Christian

**Comment by ermatitan** [comment]
Hello Christian, 

The code should distinguish if the row added is empty or not. Thanks

**Comment by ermatitan** [comment]
not fix

**Comment by christiancebudigital** [comment]
HI Erma, 

Please clear cache, it is working on our end.

Thanks,
Christian

**Comment by ermatitan** [comment]
Hello Christian, 

I have already cleared my cache and I can still recreate the problem. Thanks

**Comment by christiancebudigital** [comment]
HI Erma,

Field in now required, this is to avoid null/empty value on the field the repeater, text field.

Thanks,
Christian
