### ISSUE TITLE
Trainers : What is the function of this? Display to sidebar

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#38]
Currently, checking and unchecking this option will still display the title in the sidebar.

![image](https://cloud.githubusercontent.com/assets/12791909/9712939/c267e542-5580-11e5-80f1-2c407ecc9075.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

We have now deleted, this display to sidebar acf

Thanks,
Christian
