### ISSUE TITLE
Watch our video: Play video button is still clickable but will lead to an empty fancy box.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Evolution-MMA#45]
It should be made static or not display at all.
![image](https://cloud.githubusercontent.com/assets/11186313/9714141/816985c0-5588-11e5-954c-785256da1369.png)

**Comment by ermatitan** [comment]
Not fix. Play video button still clickable and an empty fancy button still show up when click. Closing the fancy box button will no longer recreate the problem. You need to refresh first to page in order to recreate again.

**Comment by christiancebudigital** [comment]
Hi Erma, 

Iwill not play because there was no youtube link, embedded in titan business details.

Thanks,
Christian
