### ISSUE TITLE
Classes : All Events drop down menu does not list all the created Event ACF. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#63]
![image](https://cloud.githubusercontent.com/assets/12791909/9725171/9b4cb7fa-5614-11e5-8bdb-906ddf719fc4.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

We have removed this one because this is not included in the design.

Thanks,
Christian

**Comment by ermatitan** [comment]
Hello Christian, 

Shouldn't this be removed since this is part of the plugin and the  site using all the plug-in functionality? Thanks

**Comment by christiancebudigital** [comment]
Hi Erma,

That is why we have removed this one, in the site because this is not included in the approved design, will just wait feedback for pre live fixes,. 

Thanks,
Christian
