### ISSUE TITLE
Blog single: Shouldn't we display the single post title at the banner section instead of displaying "Blog"?

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Evolution-MMA#64]
If possible have it display in this manner:

Banner section:
Single post title
breadcrumbs

On the content area:
Date
Blog content

**Comment by ermatitan** [comment]
not fix

**Comment by christiancebudigital** [comment]
Hi Erma,

Based on the approved design, this should be the format see attached screenshot, why would we change the layout if its is already client approved?
![10-evo-blog-single](https://cloud.githubusercontent.com/assets/11186331/9986495/fa759aac-606f-11e5-9530-1a11165f68ef.jpg)


Thanks,
Christian

**Comment by christiancebudigital** [comment]
this is already fixed.. please clear cache..

**Comment by ermatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12791909/10038564/630e6a0e-61fa-11e5-8fb6-27cb42040a97.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

please refer on the Design:

![10-evo-blog-single](https://cloud.githubusercontent.com/assets/11186331/10065118/a2199a98-62b3-11e5-81c1-a873252e71dd.jpg)

Thanks,
Christian

**Comment by ermatitan** [comment]
Hello Christian, 

This is why it is raised as enhancement. This was raised for consistency among single custom post in which all post title (Team/Trainer/Events) displayed on the banner . Thanks
