### ISSUE TITLE
Event single:  Clipped text in the sidebar section.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Evolution-MMA#68]
![image](https://cloud.githubusercontent.com/assets/11186313/9725633/e6349f44-5619-11e5-831c-1acdefcd342a.png)
http://evolutionmma.stage.titanweb.com.au/events/event-title-goes-here-for-two-lines-long/

**Comment by christiancebudigital** [comment]
Hi Roselie,

This is not a bug, this is the functionality of the plugin... see functionality http://quanticalabs.com/script/timetable-responsive-schedule-for-wordpress/7010836.

Thanks,
Christian

**Comment by roseliesromeo** [comment]
This bug happens if the event title exceeds one line.

**Comment by ermatitan** [comment]
Sidebar no longer shown all the upcoming events
