### ISSUE TITLE
Event single: There is no proper alignment between the page title, image and the page content.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Evolution-MMA#72]
http://evolutionmma.stage.titanweb.com.au/events/event-title-goes-here-for-two-lines-long/

![image](https://cloud.githubusercontent.com/assets/11186313/9725769/d77f19dc-561b-11e5-9fd8-567ba722073c.png)

**Comment by ermatitan** [comment]
Not Fix.

![image](https://cloud.githubusercontent.com/assets/12791909/9928835/5d23e50e-5d5b-11e5-979c-4d09707ede51.png)
