### ISSUE TITLE
Event single: What are to be displayed in the sidebar section?

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Evolution-MMA#74]
http://evolutionmma.stage.titanweb.com.au/events/event-title-goes-here-for-two-lines-long/

**Comment by christiancebudigital** [comment]
Hi Roselie,

This is the format based on the plugin we have. please visit this link
[ http://quanticalabs.com/script/timetable-responsive-schedule-for-wordpress/7010836 ]

Thanks,
Christian
