### ISSUE TITLE
Homepage: Class Timetable - Time font family attributes should be ProximaNova Extrabold

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#90]
![image](https://cloud.githubusercontent.com/assets/12791909/9728125/7de291ac-5638-11e5-9425-97cbcb1b4485.png)

**Comment by genesiscebudigital** [comment]
the designer did not provide ProximaNova Extrabold.
ProximaNova Extrabold is premium font

**Comment by christiancebudigital** [comment]
Hi Erma,

There is a font ProximaNova Extrabold.

Cheers,
Christian
