### ISSUE TITLE
Mobile : Misaligned arrow on gravity form enquiry button.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#94]
Samsung Tab 3

![image](https://cloud.githubusercontent.com/assets/12791909/9728767/dc65b73c-563c-11e5-9b92-9f91c2ea740c.png)

**Comment by ermatitan** [comment]
Not Fix

**Comment by ermatitan** [comment]
This also occurs in Samsung S4

**Comment by christiancebudigital** [comment]
Hi Erma,

please clear cache, as this is working on my s3, ang emulator on chrome, as we dont have s4 here.

Thanks,
Christian

**Comment by ermatitan** [comment]
I have already cleared my cache and problem still reproducible.

**Comment by christiancebudigital** [comment]
Hi Erma,

Will ask @bernardtitan on this issue, since we cant replicate it on our end.

Thanks,
Christian

**Comment by ermatitan** [comment]
I have recheck this issue and seems it is already fix on S4.
