### ISSUE TITLE
Homepage: Instagram testing account should not used any personal account

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Evolution-MMA#99]
![image](https://cloud.githubusercontent.com/assets/12791909/9950084/0ff39b9c-5de9-11e5-9cd1-18ce5e2ec0ab.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

We have now used, the titan instgram account.
https://instagram.com/titanuser/ - this is just for test purposes.

Thanks,
Christian
